// JOB EVENT
export const UPDATE_JOB_DETAIL = "UPDATE_JOB_DETAIL";
export const UPDATE_JOB_CLIENT = "UPDATE_JOB_CLIENT";
export const UPDATE_JOB_PROPERTY = "UPDATE_JOB_PROPERTY";
export const UPDATE_JOB_TIMESHEET = "UPDATE_JOB_TIMESHEET";
export const RESET_JOB_DETAIL = "RESET_JOB_DETAIL";
